resources:
  - name: test_github_resource
    type: GitRepo
    configuration:
      gitProvider: personal2
      path: creepy-pirate/jfrog-pipelines-test
pipelines:
  - name: test_reports
    configuration:
      environmentVariables:
        readOnly:
          reportsCount: 10
          suitesCount: 10
      retentionPolicy:
        maxAgeDays: 1
    steps:
      - name: test_report
        type: Bash
        configuration:
          inputResources:
            - name: test_github_resource
        execution:
          onExecute:
            - pushd $res_test_github_resource_resourcePath
            - npm install
            - touch .env
            - echo "REPORTS_COUNT=$reportsCount" >> .env
            - echo "SUITES_COUNT=$suitesCount" >> .env
            - TOTAL_TESTS=$(($reportsCount*$suitesCount))
            # - update_run_description "Total tests => $TOTAL_TESTS"
            # - set_run_name $TOTAL_TESTS
            - npm run test
            - save_tests $res_test_github_resource_resourcePath/
          onSuccess:
            - echo "success"
     
